version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    labels: 
      live.nic0.description: "Discord bot service"
    env_file: 
      - .env